# Generated by Django 3.0.4 on 2020-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='home_text',
            field=models.CharField(max_length=5000, verbose_name='Anasayfa Yazisi'),
        ),
    ]
