# Generated by Django 3.0.4 on 2020-03-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200316_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_upload',
        ),
    ]
