# Generated by Django 3.0.4 on 2020-03-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_post_image_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='code',
        ),
        migrations.AddField(
            model_name='post',
            name='choice',
            field=models.CharField(blank=True, choices=[('Windows 10', 'Windows 10'), ('Windows 8', 'Windows 8'), ('Linux', 'Linux')], max_length=30, null=True),
        ),
    ]
